from datetime import datetime
from io import BytesIO
from typing import Annotated

from fastapi import APIRouter, Depends, Form, HTTPException, Security, status
from fastapi.responses import Response
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.exc import IntegrityError
from sqlmodel import select

from pyrate_limiter import Duration, Limiter, Rate
from fastapi_limiter.depends import RateLimiter

from api.dependencies.auth.authentication import RedactedUserInDB, TOTPCode, Token, authenticate_user_from_db_without_totp, authorise_current_user, get_user_from_db
from api.dependencies.auth.responses import bad_credentials_exception
from api.dependencies.auth.scopes import two_factor_setup_verification_scope_manager, two_factor_access_request_token_scope_manager
from api.dependencies.auth.two_factor_authentication import verify_totp_for_token_user
from api.dependencies.scopes import get_scopes_for_role
from api.services.two_factor import check_2fa_disabled, check_2fa_enabled, get_plain_2fa_key_from_redacted_user
from api.utils.auth.hasher import get_password_hash
from api.utils.auth.token import create_access_token
from api.utils.auth.token_const import TOKEN_EXPIRY_TIMEDELTA, TWO_FACTOR_TOKEN_EXPIRY_TIMEDELTA
from api.utils.auth.two_factor_auth.totp import get_safe_otp_key, get_totp_qr_code, get_totp_uri
from db.session.session import AsyncSessionDep
from db.models.users import User, UserAccess

auth_router = APIRouter(prefix='/auth', tags=['Authentication'])

user_authentication_endpoint_rate_limit = Depends(RateLimiter(limiter=Limiter(Rate(3, Duration.SECOND * 30))))

# TODO: Update the scope manager with the correct argument once migrated, and clean up the tangle of endpoints with overlapping and incomplete goals

@auth_router.post("/register")
async def register(
    form_data: Annotated[OAuth2PasswordRequestForm, Depends()],
    session: AsyncSessionDep
):
    if not form_data.username or not form_data.password:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Provide both username and password",
        )

    pw_hash = get_password_hash(form_data.password)

    try:
        session.add(User(username=form_data.username, hash=pw_hash, two_factor_secret=get_safe_otp_key()))
        await session.commit()
    except IntegrityError:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="User with this username already exists",
        )

    return Response(status_code=status.HTTP_201_CREATED)


@auth_router.post(
    "/2fa-registration-token",
    dependencies=[user_authentication_endpoint_rate_limit],
    )
async def get_two_factor_registration_token(
    form_data: Annotated[OAuth2PasswordRequestForm, Depends()],
    session: AsyncSessionDep
    ):
    """
    Generates a token containing a user's authorised scopes, based on their internal role. 
    If the user has not verified their 2FA codes for validity, the token will always contain only the scopes necessary to verify them.
    """
    await check_2fa_disabled()
    user = await authenticate_user_from_db_without_totp(session, form_data.username, form_data.password)
        
    scopes = str(two_factor_setup_verification_scope_manager)
    access_token = create_access_token(
        data={"sub": user.username, "scope": scopes}, expires_delta=TWO_FACTOR_TOKEN_EXPIRY_TIMEDELTA
    )
    return Token(access_token=access_token, token_type="bearer")


@auth_router.get(
    "/2fa-enrol-qr",
    responses = {
        200: {
            "content": {"image/png": {}}
        }
    },

    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=Response
    )
async def get_two_factor_qr(
    current_user: Annotated[RedactedUserInDB, Security(authorise_current_user, scopes=two_factor_setup_verification_scope_manager.get_scope_array())], 
    session: AsyncSessionDep,
    ):
    # Prevent others from obtaining a means of enrolling 2fa after complete
    await check_2fa_disabled(current_user, session)
    
    plain_2fa_secret = await get_plain_2fa_key_from_redacted_user(current_user, session)
    
    qr = get_totp_qr_code(current_user.username, plain_2fa_secret)
    qr_stream = BytesIO()
    qr.save(qr_stream, format='png')
    
    return Response(content=qr_stream.getvalue(), media_type="image/png")

@auth_router.get("/2fa-enrol-uri")
async def get_two_factor_uri(
    current_user: Annotated[RedactedUserInDB, Security(authorise_current_user, scopes=two_factor_setup_verification_scope_manager.get_scope_array())], 
    session: AsyncSessionDep,
    ):
    await check_2fa_disabled(current_user, session)
    
    plain_2fa_secret = await get_plain_2fa_key_from_redacted_user(current_user, session)
    
    uri = get_totp_uri(current_user.username, plain_2fa_secret)
    
    return {'uri': uri}

@auth_router.post(
    "/2fa-verify",
    dependencies=[user_authentication_endpoint_rate_limit],
    )
async def verify_2fa_registration(
    current_user: Annotated[RedactedUserInDB, Security(authorise_current_user, scopes=two_factor_setup_verification_scope_manager.get_scope_array())], 
    session: AsyncSessionDep,
    totp_form: Annotated[TOTPCode, Form()]
    ):
    cur_timestamp = datetime.now()
    await check_2fa_disabled(current_user, session)
    
    entered_totp = totp_form.totp
    
    if not await verify_totp_for_token_user(current_user, session, entered_totp, cur_timestamp):
        raise bad_credentials_exception
    
    unredacted_user = await get_user_from_db(session, current_user.username)
    unredacted_user.two_factor_enabled = True
    unredacted_user.last_two_factor = get_password_hash(entered_totp)
    await session.commit()
    
    return Response(status_code=status.HTTP_200_OK)

# TODO: Add rate-limiting to endpoints

@auth_router.post(
    "/access-request-token",
    dependencies=[user_authentication_endpoint_rate_limit],
    )
async def get_access_request_token(
    form_data: Annotated[OAuth2PasswordRequestForm, Depends()],
    session: AsyncSessionDep
):
    if not form_data.username or not form_data.password:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Provide both username and password",
        )        
    user = await authenticate_user_from_db_without_totp(session, form_data.username, form_data.password)
    if user is None:
        raise bad_credentials_exception
    # This does trigger another query, but avoids multiple places where verification can be broken
    await check_2fa_enabled(RedactedUserInDB(username=user.username, disabled=user.disabled), session)

    scopes = str(two_factor_access_request_token_scope_manager)
    access_token = create_access_token(
        data={"sub": user.username, "scope": scopes}, expires_delta=TWO_FACTOR_TOKEN_EXPIRY_TIMEDELTA
    )
    return Token(access_token=access_token, token_type="bearer")

@auth_router.post(
    "/api-access-token",
    dependencies=[user_authentication_endpoint_rate_limit],
    )
async def get_api_access_token(
    current_user: Annotated[RedactedUserInDB, Security(authorise_current_user, scopes=two_factor_access_request_token_scope_manager.get_scope_array())], 
    session: AsyncSessionDep,
    totp_form: Annotated[TOTPCode, Form()]
    ):
    cur_timestamp = datetime.now()
    await check_2fa_enabled(current_user, session)
    
    entered_totp = totp_form.totp
    
    if not await verify_totp_for_token_user(current_user, session, totp_form.totp, cur_timestamp):
        raise bad_credentials_exception
    
    unredacted_user = await get_user_from_db(session=session, username=current_user.username)
    if unredacted_user is None:
        raise bad_credentials_exception
    
    unredacted_user.last_two_factor = get_password_hash(entered_totp)
    await session.commit()
    await session.refresh(unredacted_user)
    access_role = (await session.exec(select(UserAccess).where(UserAccess.id == unredacted_user.access_level_id))).one()
    scopes = str(get_scopes_for_role(access_role.name))
    access_token = create_access_token(
        data={"sub": current_user.username, "scope": scopes}, expires_delta=TOKEN_EXPIRY_TIMEDELTA
    )
    
    return Token(access_token=access_token, token_type="bearer")
